language: minimal

services:
  - docker

jobs:
  include:
    - script: |
        docker run -it -v ${TRAVIS_BUILD_DIR}:/repo.git -w /repo.git chapel/chapel-gasnet:1.20.0 /bin/bash -c '
        make install-deps &&
        make'
