name: CI

on: [push]

jobs:
  comm-none-build:

    runs-on: ubuntu-latest
    container:
      image: docker://chapel/chapel:1.20.0

    steps:
    - uses: actions/checkout@v1
    - name: Comm=none compile
      run: |
        cd ${GITHUB_WORKSPACE}
        apt-get update -qq && apt-get install -qq -y libhdf5-dev libzmq3-dev python3-pip
        echo "\$(eval \$(call add-path,/usr/lib/x86_64-linux-gnu/hdf5/serial/))" > Makefile.paths
        ARKOUDA_DEVELOPER=true make
        python3 --version

  gasnet-build:

    runs-on: ubuntu-latest
    container:
      image: docker://chapel/chapel-gasnet:1.20.0

    steps:
    - uses: actions/checkout@v1
    - name: Comm=gasnet compile
      run: |
        cd ${GITHUB_WORKSPACE}
        apt-get update -qq && apt-get install -qq -y libhdf5-dev libzmq3-dev python3-pip
        echo "\$(eval \$(call add-path,/usr/lib/x86_64-linux-gnu/hdf5/serial/))" > Makefile.paths
        ARKOUDA_DEVELOPER=true make
