name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: free -g
    - name: Run a multi-line script
      uses: docker://chapel/chapel:1.20.0
      with:
        entrypoint: chpl --version
