name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: docker://chapel/chapel:1.20.0
 

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        cd ${GITHUB_WORKSPACE}
        apt-get -q update && apt-get install -y -q libhdf5-dev libzmq3-dev python3-pip
        ls
        pwd
        echo "\$(eval \$(call add-path,/usr/lib/x86_64-linux-gnu/hdf5/serial/))" > Makefile.paths
        ARKOUDA_DEVELOPER=true make
