name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: free -g
    - name: Run a multi-line script
      uses: docker://chapel/chapel:1.20.0
      with:
        entrypoint: /bin/bash
        args: -c 'apt-get update && apt-get install -y libhdf5-dev libzmq3-dev python3-pip &&
        echo "\$(eval \$(call add-path,/usr/lib/x86_64-linux-gnu/hdf5/serial/))" > Makefile.paths &&
        ARKOUDA_DEVELOPER=true make'
